### ISSUE TITLE
okay may be missing something here... is there a default password 

### ISSUE THREAD

**Issue by Mwilloughby1982** [genesis-community/shield-genesis-kit#10]
just deployed shield and tried accessing the web interface. Didnt see anywhere in genesis when deploying to put a password is there a defualt password or somewhere in vault it is hiding?

**Comment by jhunt** [comment]
Use the default SHIELD failsafe account, `admin` / `shield`

see https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/core/spec#L49-L54
