### ISSUE TITLE
Sheild deployment failed

### ISSUE THREAD

**Issue by bala151187** [genesis-community/shield-genesis-kit#22]
search hit BOTTOM, continuing at TOP
  - based on kit shield/1.10.2
  - to 'ops' BOSH director.

Checking availability of the 'ops' BOSH director...ok - authenticated as admin

Downloading configs from 'ops' BOSH director...
  [✔ ] all cloud configs:
       [✔ ] base cloud config

[ops] running BOSH configs and environmental parameters checks...
  [Checking cloud config]
    [✘ ] vm_type 'small' exists
    [✔ ] disk_type 'shield' exists
    [✔ ] network 'shield' exists
  cloud config [FAILED]

[ops] running secrets checks...

Validating 5 secrets for ops under path '/secret/ops/shield/':
Completed - Duration: 0 seconds [5 validated/0 skipped/0 errors]

Preflight checks failed; deployment operation halted.

my manifest.yml
---
kit:
  name:    shield
  version: 1.10.2
  features: []

genesis:
  env:                ops
  shield_vm_type: shield
  min_version:        2.7.6

params:
  shield_static_ip: x.x.x.x

Since the vm_type moved under genesis . so the shield deployment failed.

**Comment by dennisjbell** [comment]
The problem is that `shield_vm_type` needs to be under `params`, not `genesis`

**Comment by michaelmccaskill** [comment]
I think what Bala failed to mention was the was the way env file was generated using `genesis new`, meaning there's a bug in `new` hook.
